recruiting_service/recruiting_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('service.urls', 'service'), namespace='service')),
]

recruiting_service/service/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('recruit/', views.add_recruit, name='recruit'),
    path('test/<int:recruit_id>', views.test_recruit, name='test'),
    path('sith/', views.list_sith, name='sith'),
    path('list_of_recruits/<int:sith_id>', views.list_of_recruits, name='list_of_recruits'),
    path('list_of_recruits/<int:sith_id>/<int:recruit_id>', views.recruit_detail, name='recruit_detail'),
    path('accepted/<int:sith_id>/<int:recruit_id>/', views.accepted, name='accepted'),
]

recruiting_service/service/models.py
from django.db import models


class Planet(models.Model):
    name = models.CharField(max_length=200)
    objects = models.Manager()

    def __str__(self):
        return self.name


class Sith(models.Model):
    name = models.CharField(max_length=200)
    planet_of_teaching = models.ForeignKey(Planet, on_delete=models.CASCADE)
    objects = models.Manager()

    def __str__(self):
        return self.name


class Recruit(models.Model):
    name = models.CharField(max_length=200)
    planet_of_living = models.ForeignKey(Planet, on_delete=models.CASCADE)
    age = models.IntegerField()
    email = models.EmailField()
    accepted = models.BooleanField(default=False)
    sith = models.ForeignKey(Sith, on_delete=models.CASCADE, blank=True, null=True)
    objects = models.Manager()

    def __str__(self):
        return self.name


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    answer = models.BooleanField(default=False)
    objects = models.Manager()

    def __str__(self):
        return self.question_text


class Result(models.Model):
    recruit = models.ForeignKey(Recruit, on_delete=models.CASCADE, related_name='recruit')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='question')
    result = models.BooleanField('Результат', default=False)
    objects = models.Manager()

recruiting_service/service/forms.py
from django import forms

from .models import Recruit, Planet, Result


class RecruitForm(forms.ModelForm):
    name = forms.CharField(max_length=200, label='Имя')
    planet_of_living = forms.ModelChoiceField(queryset=Planet.objects.all(), label='Планета проживания')
    age = forms.IntegerField(label='Возраст')
    email = forms.EmailField(label='Email')

    class Meta:
        model = Recruit
        fields = ['name', 'planet_of_living', 'age', 'email']


CHOICES = [('True', 'Да'), ('False', 'Нет')]


class PollForm(forms.ModelForm):
    result = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES, label='Ответ')

    class Meta:
        model = Result
        fields = ['question', 'result']
        labels = {
            'question': 'Вопрос',
        }

recruiting_service/service/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import RecruitForm, PollForm
from .models import Planet, Question, Recruit, Sith, Result
from django.forms import formset_factory, modelformset_factory
from django.core.mail import send_mail


# Create your views here.

def index(request):
    return render(request, 'service/index.html')


def add_recruit(request):
    if request.method != 'POST':
        form = RecruitForm()
    else:
        form = RecruitForm(data=request.POST)
        if form.is_valid():
            recruit = form.save()
            recruit.refresh_from_db()
            recruit.save()
            # return HttpResponseRedirect(reverse('service:test'))
            return HttpResponseRedirect(reverse('service:test', kwargs={"recruit_id": recruit.id}))
    context = {'form': form}
    return render(request, 'service/recruitform.html', context)


def test_recruit(request, recruit_id):
    recruit = Recruit.objects.get(id=recruit_id)
    questions = Question.objects.all()
    PollFormSet = formset_factory(form=PollForm, extra=3)
    if request.method != 'POST':
        formset = PollFormSet()
    else:
        formset = PollFormSet(request.POST)
        if formset.is_valid():
            for form in formset:
                test_results = form.save(commit=False)
                test_results.recruit = recruit
                test_results.save()
            return HttpResponseRedirect(reverse('service:index'))
    context = {'formset': formset, 'questions': questions}
    return render(request, "service/testform.html", context)


def list_sith(request):
    siths = Sith.objects.all()
    context = {'siths': siths}
    return render(request, 'service/sith.html', context)


def list_of_recruits(request, sith_id):
    sith = Sith.objects.get(id=sith_id)
    recruits = Recruit.objects.filter(accepted=False, planet_of_living=sith.planet_of_teaching)
    context = {'recruits': recruits, 'sith_id': sith_id}
    return render(request, 'service/list_of_recruits.html', context)


def recruit_detail(request, sith_id, recruit_id):
    recruit = Recruit.objects.get(id=recruit_id)
    results = Result.objects.filter(recruit_id=recruit_id)
    context = {'recruit': recruit, 'results': results, 'sith_id': sith_id}
    return render(request, 'service/recruit_detail.html', context)


def accepted(request, sith_id, recruit_id):
    recruit = Recruit.objects.get(id=recruit_id)
    sith = Sith.objects.get(id=sith_id)
    if sith.recruit_set.count() <= 3:
        recruit.accepted = True
        recruit.sith = sith
        recruit.save()
        send_mail(
            'Вы приняты!',
            'дада вы приняты',
            'be11a@yandex.ru',
            [recruit.email]
        )
        return HttpResponseRedirect(reverse('service:list_of_recruits', kwargs={"sith_id": sith_id}))
    elif sith.recruit_set.count() > 3:
        messages.error(request, "У вас не может быть больше 3 рук Тени")
        return recruit_detail(request, sith_id, recruit_id)

recruiting_service/service/templates/service/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'service/style.css' %}">
    <title>Служба рекрутинга</title>
</head>

<body>
    <nav class="nav justify-content-center">
        {% block nav %}{% endblock %}
    </nav>
    <main class="container-fluid ">
        <div class="row parent justify-content-center">
            {% block main %}{% endblock %}
        </div>
    </main>
</body>

</html>

recruiting_service/service/templates/service/index.html
{% extends "service/base.html" %}

{% block nav %}
<a href="{% url 'service:recruit' %}" class="nav-link">Для рекрутов</a>
<a href="{% url 'service:sith' %}" class="nav-link">Для ситхов</a>
<a href="" class="nav-link">Бонусная секция</a>
{% endblock %}

recruiting_service/service/templates/service/list_of_recruits.html
{% extends "service/base.html" %}
{% block main %}

<ul class="text-center">
    {% for recruit in recruits %}
    <li>
        <a href="{% url 'service:recruit_detail' sith_id recruit.id %}">
            {{recruit}}
        </a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

recruiting_service/service/templates/service/recruit_detail.html
{% extends "service/base.html" %}
{% block main %}
<div class="col-3 text-center">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>вопрос</th>
                <th>ответ</th>
            </tr>
        </thead>
        <tbody>
            {% for res in results %}
            <tr>
                <td>{{ res.question }}</td>
                <td>{{ res.result }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="col-1">
    <form action="{% url 'service:accepted' sith_id recruit.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-dark">Принять</button>
    </form>
</div>
{% if messages %}
                {% for message in messages %}
                    {{message}}
                {% endfor %}
            {% endif %}
{% endblock %}

recruiting_service/service/templates/service/recruitform.html
{% extends "service/base.html" %}
{% load crispy_forms_tags %}
{% block main %}
<form action="{% url 'service:recruit' %}" method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button name="submit" class="btn btn-dark">Далее</button>
</form>
{% endblock %}

recruiting_service/service/templates/service/sith.html
{% extends "service/base.html" %}
{% block main %}
<div class="col-3 text-center">
    <table class="table table-borderless">
        <thead class="thead-dark">
            <tr>
                <th>Ситх</th>
                <th>Количество Рук Тени</th>
            </tr>
        </thead>
        <tbody>
            {% for sith in siths %}
            <tr>
                <td><a href="{% url 'service:list_of_recruits' sith.id %}">{{sith}}</a></td>
                <td>{{ sith.recruit_set.count }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

recruiting_service/service/templates/service/testform.html
{% extends "service/base.html" %}
{% load crispy_forms_tags %}
{% block main %}
<div class="col-3">
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ formset.management_form }}
    {% for form in formset.forms %}
    {{form|crispy}}
    {% endfor %}
    <button name="submit" class="btn btn-dark">Сохранить</button>
</form>
</div>

{% endblock %}
</div>